### ISSUE TITLE
Bitwig not recognizing the PCR-300

### ISSUE THREAD

**Issue by carlosguerra3** [klingtnet/bitwig-edirol-pcr#2]
I followed all the instructions, I have firmware 1.05, the controller files are in the bigwig controllers scripts location and for some reason Bitwig doesn't recognize the controller.

Any help will be appreciated.

Carlos

**Comment by klingtnet** [comment]
Hi,

are you using Windows or Mac? If so, I would like to know the names of the PCR controller's ports as shown in `Settings → Controllers` so I can fix them in the controller script.

**Comment by klingtnet** [comment]
PS: It should be three input and two output ports.

**Comment by carlosguerra3** [comment]
Hi, I'm using a Mac, here are the MIDI ports displayed in the:

-Audio MIDI Setup.
1st new external device | PCR MIDI OUT
2nd new external device | PCR
3rd new external device | PCR MIDI IN
4th new external device | PCR 1
5th new external device | PCR 2

-Bitwig settings.
PCR MIDI IN
PCR 1
PCR 2

**Comment by klingtnet** [comment]
Please try out the [0.9.1 release](https://github.com/klingtnet/bitwig-edirol-pcr/releases/tag/0.9.1).

**Comment by carlosguerra3** [comment]
Hi, I tried 0.9.1 but still having the same issue.

The only way to show activity is using PCR 1 as a Generic Keyboard.

In Bitwig - Detect available controllers will not detect the PCR and Edirol or PCR is not listed on the list of manual controllers.

I'm using Control Map 0

**Comment by klingtnet** [comment]
Can you provide a screenshot of Bitwig's `Settings → Controllers` menu?

**Comment by klingtnet** [comment]
Update: It should be possible to add the controller script manually and then assigning the controller ports: `Settings → Controllers → Add controller manually → Edirol → Edirol PCR (by klingt.net)`

![screenshot-1531166142](https://user-images.githubusercontent.com/1538057/42472914-424c223c-83c3-11e8-8f67-2dc5e455dca8.png)

If the controller script is not listed then it can't be found by Bitwig, obviously.

**Comment by klingtnet** [comment]
Please put the `Extension` (this is not one of the Javascript Controller Scripts) into `~/Bitwig Studio/Extensions` as for example stated in [one of my other Bitwig Extensions](https://github.com/klingtnet/bitwig-akai-midimix#installation). I think it should work then. Nonetheless, I will update the installation instructions.

**Comment by carlosguerra3** [comment]
Hi, here is the screenshot of the Bitwig's Settings → Controllers menu, and the MacOS MIDI Configuration

![screen shot 2018-07-09 at 5 50 13 am](https://user-images.githubusercontent.com/23441019/42482638-5658bc78-83ae-11e8-8a90-0b48a5b5712a.png)

![screen shot 2018-07-09 at 7 32 32 pm](https://user-images.githubusercontent.com/23441019/42482735-ed1117fa-83ae-11e8-9dbf-c1e3ee247d4d.png)



![screen shot 2018-07-09 at 5 48 57 am](https://user-images.githubusercontent.com/23441019/42482703-b3b18b98-83ae-11e8-9c58-fff229a270fd.png)

**Comment by klingtnet** [comment]
@carlosguerra3 Thank you for the screenshots. Did you read this comment: https://github.com/klingtnet/bitwig-edirol-pcr/issues/2#issuecomment-403602344 ?

**Comment by carlosguerra3** [comment]
Cool! it works now, I followed the instructions on your other extension. This is how I'm mapping the ports.

![screen shot 2018-07-10 at 10 46 45 pm](https://user-images.githubusercontent.com/23441019/42549823-dad32796-8493-11e8-90db-db6b7b5d016a.png)

![screen shot 2018-07-10 at 10 51 28 pm](https://user-images.githubusercontent.com/23441019/42549835-e45da278-8493-11e8-8fa6-cc3416cf29d7.png)

**Comment by carlosguerra3** [comment]
Looks like the mapping is working OK, but I'm discovering what is what.

For example the transport buttons work but you have to hold them to keep them active instead of toggling.

**Comment by klingtnet** [comment]
@carlosguerra3 Thank you for reporting back, glad that it works now (somehow).

> For example the transport buttons work but you have to hold them to keep them active instead of toggling.

I will check the transport button handler.
Can you please open a separate issue if there are more problems (this is one is resolved)?

**Comment by klingtnet** [comment]
@carlosguerra3 I fixed the transport buttons behavior in 0.9.2

Please open a new issue if you encounter any problems/bugs.
